#!/bin/sh

t="$1"
here=`pwd`

top_srcdir=${top_srcdir:-$here/../..}
top_srcdir=`cd $top_srcdir && pwd`

# the perl program
PERL=${PERL:-perl}

GOLDEN_DIR=${srcdir}/outputs
INPUT_DIR=${srcdir}/inputs

TESTLIST=${srcdir}/tests.list

rundir=${here}/run


# figure out what files we need to copy for this test and what
# arguments to feed refdes_renum
files=`grep "^[ \t]*${t}[ \t]*|" $TESTLIST | awk 'BEGIN{FS="|"} {print $2}'`
args=`grep "^[ \t]*${t}[ \t]*|" $TESTLIST | awk 'BEGIN{FS="|"} {print $3}'`
code=`grep "^[ \t]*${t}[ \t]*|" $TESTLIST | awk 'BEGIN{FS="|"} {print $4}'`
if test "X$code" = "X" ; then
    code=0
fi


# create temporary run directory
if test ! -d $rundir ; then
    mkdir -p $rundir
fi

# Create the files needed
if test ! -z "$files" ; then
    for f in $files ; do
	cp ${INPUT_DIR}/${f} ${rundir}
	chmod 644 ${rundir}/${f}
    done
fi

# run refdes_renum
#

echo "${PERL} -w ${top_srcdir}/scripts/refdes_renum $args $files"
cd ${rundir} && ${PERL} -w ${top_srcdir}/scripts/refdes_renum $args $files
rc=$?
if test $rc -ne $code ; then
    echo "FAILED:  refdes_renum returned $rc which did not match the expected $code"
    exit 1
fi

status=0

for f in ${files} ; do
    ref=${GOLDEN_DIR}/${t}/${f}
    out=${rundir}/${f}

    if test "X$regen" = "Xyes" ; then
	cp ${out} ${ref}
	echo "Regenerated ${ref}"
    elif test -f ${ref} ; then
	if diff -w ${ref} ${out} >/dev/null ; then
	    echo "PASS"
	else
	    echo "FAILED:  See diff -w ${ref} ${out}"
	    status=1
	fi
    else
	echo "No reference file.  Skipping"
	status=77
    fi
done

cd $here

# clean up the rundirectory
rm -fr ${rundir}

exit ${status}
